//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matthewrozendaal.com.Areas.KidsList.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KidsListDatabaseEntity : DbContext
    {
        public KidsListDatabaseEntity()
            : base("name=KidsListDatabaseEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Point_Changes> Point_Changes { get; set; }
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<Profile_Pic> Profile_Pic { get; set; }
    }
}
