//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matthewrozendaal.com.Areas.KidsList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point_Changes
    {
        public int PC_ID { get; set; }
        public Nullable<int> kid_ID { get; set; }
        public Nullable<int> point_id { get; set; }
        public Nullable<System.DateTime> dateStamp { get; set; }
        public Nullable<int> infringement_change { get; set; }
        public Nullable<int> increment_exponential { get; set; }
        public string note { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Point Point { get; set; }
    }
}
