//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matthewrozendaal.com.Areas.KidsList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Pic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile_Pic()
        {
            this.People = new HashSet<Person>();
        }
    
        public int Pic_ID { get; set; }
        public byte[] picture { get; set; }
        public string Picture_alt { get; set; }
        public string Picture_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
    }
}
