//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matthewrozendaal.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PeopleID { get; set; }
        public int UserID { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int parent_ID { get; set; }
        public Nullable<int> profile_ID { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<int> max_gift { get; set; }
        public Nullable<int> min_gift { get; set; }
        public Nullable<System.DateTime> goal_endDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Profile_Pic Profile_Pic { get; set; }
    }
}
