//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matthewrozendaal.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public Point()
        {
            this.Point_Changes = new HashSet<Point_Changes>();
        }
    
        public int point_ID { get; set; }
        public string name { get; set; }
        public Nullable<int> value_start { get; set; }
    
        public virtual ICollection<Point_Changes> Point_Changes { get; set; }
    }
}
