//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matthewrozendaal.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point_Changes
    {
        public int ID { get; set; }
        public int Kid_Id { get; set; }
        public int Point_Id { get; set; }
        public System.DateTime Change_Date { get; set; }
        public Nullable<int> InfringmentChange { get; set; }
        public Nullable<bool> IncrementExpo { get; set; }
        public string Note { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Point Point { get; set; }
    }
}
