//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matthewrozendaal.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Pic
    {
        public Profile_Pic()
        {
            this.People = new HashSet<Person>();
        }
    
        public int picture_id { get; set; }
        public byte[] picture { get; set; }
        public string picture_alt { get; set; }
        public string picture_name { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
