//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matthewrozendaal.com.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class KidsListDatabaseEntity : DbContext
    {
        public KidsListDatabaseEntity()
            : base("name=KidsListDatabaseEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Point_Changes> Point_Changes { get; set; }
        public DbSet<Point> Points { get; set; }
        public DbSet<Profile_Pic> Profile_Pic { get; set; }
    
        public virtual int CreateNewUser(string userName, string passwords)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordsParameter = passwords != null ?
                new ObjectParameter("passwords", passwords) :
                new ObjectParameter("passwords", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateNewUser", userNameParameter, passwordsParameter);
        }
    
        public virtual int UpdateGifts(Nullable<int> p_UserID, Nullable<int> p_Max_gift, Nullable<int> p_Min_gift)
        {
            var p_UserIDParameter = p_UserID.HasValue ?
                new ObjectParameter("p_UserID", p_UserID) :
                new ObjectParameter("p_UserID", typeof(int));
    
            var p_Max_giftParameter = p_Max_gift.HasValue ?
                new ObjectParameter("p_Max_gift", p_Max_gift) :
                new ObjectParameter("p_Max_gift", typeof(int));
    
            var p_Min_giftParameter = p_Min_gift.HasValue ?
                new ObjectParameter("p_Min_gift", p_Min_gift) :
                new ObjectParameter("p_Min_gift", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateGifts", p_UserIDParameter, p_Max_giftParameter, p_Min_giftParameter);
        }
    
        public virtual int UpdateParentID(Nullable<int> p_UserId, Nullable<int> p_parent_ID)
        {
            var p_UserIdParameter = p_UserId.HasValue ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(int));
    
            var p_parent_IDParameter = p_parent_ID.HasValue ?
                new ObjectParameter("p_parent_ID", p_parent_ID) :
                new ObjectParameter("p_parent_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateParentID", p_UserIdParameter, p_parent_IDParameter);
        }
    
        public virtual int UpdatePeopleName(Nullable<int> p_UserId, string p_firstname, string p_lastname)
        {
            var p_UserIdParameter = p_UserId.HasValue ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(int));
    
            var p_firstnameParameter = p_firstname != null ?
                new ObjectParameter("p_firstname", p_firstname) :
                new ObjectParameter("p_firstname", typeof(string));
    
            var p_lastnameParameter = p_lastname != null ?
                new ObjectParameter("p_lastname", p_lastname) :
                new ObjectParameter("p_lastname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePeopleName", p_UserIdParameter, p_firstnameParameter, p_lastnameParameter);
        }
    
        public virtual int UpdatePoints(Nullable<int> p_UserID, Nullable<int> p_PointChange)
        {
            var p_UserIDParameter = p_UserID.HasValue ?
                new ObjectParameter("p_UserID", p_UserID) :
                new ObjectParameter("p_UserID", typeof(int));
    
            var p_PointChangeParameter = p_PointChange.HasValue ?
                new ObjectParameter("p_PointChange", p_PointChange) :
                new ObjectParameter("p_PointChange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePoints", p_UserIDParameter, p_PointChangeParameter);
        }
    
        public virtual int UpdateUser(Nullable<int> p_userID, string p_firstname, string p_lastname, Nullable<int> p_parent_ID, Nullable<int> p_profile_ID, Nullable<int> p_max_gift, Nullable<int> p_min_gift, Nullable<System.DateTime> p_goal_endDate)
        {
            var p_userIDParameter = p_userID.HasValue ?
                new ObjectParameter("p_userID", p_userID) :
                new ObjectParameter("p_userID", typeof(int));
    
            var p_firstnameParameter = p_firstname != null ?
                new ObjectParameter("p_firstname", p_firstname) :
                new ObjectParameter("p_firstname", typeof(string));
    
            var p_lastnameParameter = p_lastname != null ?
                new ObjectParameter("p_lastname", p_lastname) :
                new ObjectParameter("p_lastname", typeof(string));
    
            var p_parent_IDParameter = p_parent_ID.HasValue ?
                new ObjectParameter("p_parent_ID", p_parent_ID) :
                new ObjectParameter("p_parent_ID", typeof(int));
    
            var p_profile_IDParameter = p_profile_ID.HasValue ?
                new ObjectParameter("p_profile_ID", p_profile_ID) :
                new ObjectParameter("p_profile_ID", typeof(int));
    
            var p_max_giftParameter = p_max_gift.HasValue ?
                new ObjectParameter("p_max_gift", p_max_gift) :
                new ObjectParameter("p_max_gift", typeof(int));
    
            var p_min_giftParameter = p_min_gift.HasValue ?
                new ObjectParameter("p_min_gift", p_min_gift) :
                new ObjectParameter("p_min_gift", typeof(int));
    
            var p_goal_endDateParameter = p_goal_endDate.HasValue ?
                new ObjectParameter("p_goal_endDate", p_goal_endDate) :
                new ObjectParameter("p_goal_endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", p_userIDParameter, p_firstnameParameter, p_lastnameParameter, p_parent_IDParameter, p_profile_IDParameter, p_max_giftParameter, p_min_giftParameter, p_goal_endDateParameter);
        }
    }
}
